# Generated by Django 4.1.7 on 2023-03-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_login_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_method',
        ),
    ]
