# Generated by Django 4.1.7 on 2023-03-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_login_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'github'), ('google', 'google')], default='email', max_length=50),
        ),
    ]
