# Generated by Django 4.1.3 on 2022-11-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_address_alter_room_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(to='rooms.amenity'),
        ),
        migrations.AlterField(
            model_name='room',
            name='baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='room',
            name='facilities',
            field=models.ManyToManyField(to='rooms.facility'),
        ),
        migrations.AlterField(
            model_name='room',
            name='house_rules',
            field=models.ManyToManyField(to='rooms.houserule'),
        ),
    ]
