# Generated by Django 4.1.3 on 2022-11-18 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='check_in',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='check_out',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
