# Generated by Django 4.1.7 on 2023-03-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_room_amenities_alter_room_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='persons',
            field=models.IntegerField(help_text='how many people will be staying'),
        ),
    ]
