# Generated by Django 4.1.7 on 2023-05-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_alter_room_facilities'),
        ('lists', '0006_alter_list_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='lists', to='rooms.room'),
        ),
    ]
