# Generated by Django 4.1.7 on 2023-04-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookedday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookedDay',
        ),
    ]
